root: true
env:
  es2021: true
  node: true
extends:
  - "@liatrio/eslint-config"
parserOptions:
  ecmaVersion: 11
rules:
  "implicit-arrow-linebreak": "off"
  "max-len":
    - "error"
    - code: 120
      ignoreStrings: true
      ignoreTemplateLiterals: true
  "no-await-in-loop": "off" # TODO: refactor our usage of async / await to take advantage of `Promise.all` and remove this
  "no-console": "off"
  "security/detect-non-literal-require": "off"
  "security/detect-non-literal-fs-filename": "off"
  "security/detect-object-injection": "off"
  "unicorn/no-await-expression-member": "off"
