root: true
env:
  es2021: true
  node: true
extends:
  - "@liatrio/eslint-config"
parserOptions:
  ecmaVersion: 2022
  sourceType: module
rules:
  "implicit-arrow-linebreak": "off"
  "max-len":
    - "error"
    - code: 120
      ignoreStrings: true
      ignoreTemplateLiterals: true
  "no-await-in-loop": "off"
  "no-process-exit": "off"
  "security/detect-non-literal-require": "off"
  "security/detect-non-literal-fs-filename": "off"
  "security/detect-object-injection": "off"
  "unicorn/no-await-expression-member": "off"
  "unicorn/no-process-exit": "off"
  "node/no-missing-import": "off"
