name: "eslint"

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: yarn install
        working-directory: app

      - name: Lint
        run: yarn run lint
        working-directory: app
