name: Packer

on:
  workflow_dispatch: {}

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@85839311bf6d0a1a8e0bd26dfac5311bc9f7d6ad
        with:
          command: validate
          arguments: -syntax-only
          target: ubuntu.pkr.hcl
          working_directory: packer

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@85839311bf6d0a1a8e0bd26dfac5311bc9f7d6ad
        with:
          command: build
          arguments: >
            -color=false
            -on-error=abort
            -var-file=variables.pkr.hcl
          target: ubuntu.pkr.hcl
          working_directory: packer
        env:
          PACKER_LOG: 1
          AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SIG_SUBSCRIPTION_ID }}"
          AZURE_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
          AZURE_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
